name: eigen1

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - ag-ui-protocol==0.1.7
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.13
    - aioredis==2.0.1
    - aiosignal==1.3.2
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - aliyun-python-sdk-sts==3.1.2
    - annotated-types==0.7.0
    - argcomplete==3.6.2
    - async-timeout==5.0.1
    - attrs==25.3.0
    - Authlib==1.6.0
    - backports.tarfile==1.2.0
    - bcrypt==4.3.0
    - bidict==0.23.1
    - blinker==1.9.0
    - bohr-agent-sdk==0.1.14
    - bson==0.5.10
    - build==1.2.2.post1
    - camel==0.1.2
    - camel-ai==0.2.68
    - certifi==2025.6.15
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - click==8.2.1
    - colorama==0.4.6
    - contourpy==1.3.2
    - crcmod==1.7
    - cryptography==41.0.7
    - cycler==0.12.1
    - dargs==0.4.10
    - distro==1.9.0
    - dnspython==2.7.0
    - docstring-parser==0.15
    - docutils==0.21.2
    - dpdispatcher==0.6.9
    - eventlet==0.40.1
    - exceptiongroup==1.3.0
    - fastapi
    - fastmcp==2.9.0
    - Flask==2.3.3
    - Flask-SocketIO==5.3.6
    - fonttools==4.58.4
    - frozenlist==1.7.0
    - gevent==23.9.1
    - greenlet==3.2.3
    - gunicorn==21.2.0
    - h11==0.16.0
    - hiredis==2.4.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - httpx-sse==0.4.1
    - id==1.5.0
    - idna==3.10
    - importlib_metadata==8.7.0
    - itsdangerous==2.2.0
    - jaraco.classes==3.4.0
    - jaraco.context==6.0.1
    - jaraco.functools==4.2.1
    - jeepney==0.9.0
    - Jinja2==3.1.6
    - jiter==0.10.0
    - jmespath==0.10.0
    - jsonpatch==1.33
    - jsonpickle==4.1.1
    - jsonpointer==3.0.0
    - jsonschema==4.24.0
    - jsonschema-specifications==2025.4.1
    - keyring==25.6.0
    - kiwisolver==1.4.8
    - lbg==1.2.29
    - markdown-it-py==3.0.0
    - MarkupSafe==3.0.2
    - matplotlib==3.10.3
    - mcp==1.9.4
    - mdurl==0.1.2
    - more-itertools==10.7.0
    - multidict==6.5.1
    - nest-asyncio==1.6.0
    - nh3==0.2.21
    - numpy==2.2.6
    - openai==1.91.0
    - openapi-pydantic==0.5.1
    - oss2==2.19.1
    - packaging==25.0
    - paho-mqtt==2.1.0
    - pandas==2.3.0
    - paramiko==3.5.1
    - pillow==10.4.0
    - prometheus_client==0.22.1
    - propcache==0.3.2
    - psutil==5.9.8
    - pycparser==2.22
    - pycryptodome==3.23.0
    - pydantic==2.11.7
    - pydantic-settings==2.10.1
    - pydantic_core==2.33.2
    - Pygments==2.19.2
    - pyhumps==3.8.0
    - PyJWT==2.9.0
    - PyNaCl==1.5.0
    - pyparsing==3.2.3
    - PyPDF2==3.0.1
    - pyproject_hooks==1.2.0
    - pyreadline==2.1
    - pyreadline3==3.5.4
    - pytimeparse==1.1.8
    - pytz==2025.2
    - PyYAML==6.0.2
    - readchar==4.2.1
    - readme_renderer==44.0
    - redis==6.2.0
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.4
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==14.0.0
    - rpds-py==0.25.1
    - SecretStorage==3.3.3
    - setproctitle==1.3.6
    - shellingham==1.5.4
    - simple-websocket==1.1.0
    - six==1.17.0
    - sniffio==1.3.1
    - sounddevice==0.5.2
    - sse-starlette==2.3.6
    - sseclient-py==1.8.0
    - starlette==0.27.0
    - tiktoken==0.7.0
    - tqdm==4.67.1
    - twine==6.1.0
    - typeguard==4.4.4
    - typer==0.16.2
    - typing-inspection==0.4.1
    - typing_extensions==4.14.0
    - tzdata==2025.2
    - ujson==5.10.0
    - urllib3==2.5.0
    - uvicorn==0.24.0
    - uvloop==0.21.0
    - validators==0.35.0
    - watchfiles==1.1.0
    - websocket-client==1.8.0
    - websockets==15.0.1
    - Werkzeug==3.1.3
    - wsproto==1.2.0
    - yarl==1.20.1
    - zipp==3.23.0
    - zope.event==5.0
    - zope.interface==7.2
    - tenacity
    - markdown
    - weasyprint
    - unidecode
    - langid
    - termcolor
    - hipporag
    - ipdb